### ISSUE TITLE
Windows 9.1.0 - Fail to login

### ISSUE THREAD

**Issue by Rakdos8** [conversejs/converse-desktop#23]
I fail to login using the Converse Desktop but the same login/password on the demo page (here : https://conversejs.org/fullscreen.html) is working.

In the console the only log are :
```txt
connection.js:79          GET https://random.com/.well-known/host-meta 404
discoverConnectionMethods @ connection.js:79
discoverConnectionMethods @ loginform.js:73
await in discoverConnectionMethods (async)
onLoginFormSubmitted @ loginform.js:51
handleEvent @ lit-html.ts:2047
log.js:66  2022-08-01T13:52:01.927Z WARNING: Could not discover XEP-0156 connection methods 
log @ log.js:66
warn @ log.js:89
discoverConnectionMethods @ connection.js:88
await in discoverConnectionMethods (async)
discoverConnectionMethods @ loginform.js:73
await in discoverConnectionMethods (async)
onLoginFormSubmitted @ loginform.js:51
handleEvent @ lit-html.ts:2047
```

The same logs are found on the main demo page.

**Comment by licaon-kter** [comment]
The error is on top, so you say you can access `https://random.com/.well-known/host-meta` just fine?

**Comment by Rakdos8** [comment]
No this link leads to a 404 but looks to not be mandatory. In fact, it's working just fine with the fullscreen demo page and the same error occurs there.

**Comment by licaon-kter** [comment]
Odd, the console log of the webpage shows that being used just fine?

**Comment by Rakdos8** [comment]
Yeah, on the demo page everything is going fine. I still have some JS errors (see below) but it's connected and working.

[Logs on fullscreen demo page](https://conversejs.org/fullscreen.html) :
```txt
log.js:66  2022-08-01T14:51:22.747Z WARNING: Could not restore session for jid: freyers@random.com/converse.js-38523992 Error message: _restore: no restoreable session. 
log @ log.js:66
warn @ log.js:89
ul.restoreBOSHSession @ bosh.js:95
await in ul.restoreBOSHSession (async)
login @ core.js:218
await in login (async)
connect @ loginform.js:92
onLoginFormSubmitted @ loginform.js:56
handleEvent @ lit-html.ts:2047
fullscreen.html:1 Access to fetch at 'https://random.com/.well-known/host-meta' from origin 'https://conversejs.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.js:82          GET https://random.com/.well-known/host-meta net::ERR_FAILED 404
discoverConnectionMethods @ index.js:82
connect @ index.js:106
Fc @ init.js:353
Lc @ init.js:293
login @ core.js:226
await in login (async)
connect @ loginform.js:92
onLoginFormSubmitted @ loginform.js:56
handleEvent @ lit-html.ts:2047
log.js:64  ERROR: Failed to discover alternative connection methods at https://random.com/.well-known/host-meta
log @ log.js:64
error @ log.js:81
discoverConnectionMethods @ index.js:84
await in discoverConnectionMethods (async)
connect @ index.js:106
Fc @ init.js:353
Lc @ init.js:293
login @ core.js:226
await in login (async)
connect @ loginform.js:92
onLoginFormSubmitted @ loginform.js:56
handleEvent @ lit-html.ts:2047
log.js:64  ERROR: TypeError: Failed to fetch    at Oc.discoverConnectionMethods (https://conversejs.org/dist/converse.min.js:2:189282)    at Oc.connect (https://conversejs.org/dist/converse.min.js:2:189626)    at Fc (https://conversejs.org/dist/converse.min.js:2:200508)    at Lc (https://conversejs.org/dist/converse.min.js:2:198627)    at Object.login (https://conversejs.org/dist/converse.min.js:2:247154)
log @ log.js:64
error @ log.js:81
discoverConnectionMethods @ index.js:85
await in discoverConnectionMethods (async)
connect @ index.js:106
Fc @ init.js:353
Lc @ init.js:293
login @ core.js:226
await in login (async)
connect @ loginform.js:92
onLoginFormSubmitted @ loginform.js:56
handleEvent @ lit-html.ts:2047
controlbox.js:10 connection_status
controlbox.js:11 1
log.js:72  2022-08-01T14:51:24.409Z INFO: SASL authentication succeeded. 
controlbox.js:10 connection_status
controlbox.js:11 5
```

**Comment by kicken** [comment]
The demo page provides a fallback connection manager that will be used if one cannot be found via the .well-known/host-meta file, the desktop application does not.

**Comment by Rakdos8** [comment]
> The demo page provides a fallback connection manager that will be used if one cannot be found via the .well-known/host-meta file, the desktop application does not.

Thank you for the explanation ! Could it be included in the roadmap or it's not even doable ?

**Comment by kicken** [comment]
> Thank you for the explanation ! Could it be included in the roadmap or it's not even doable ?

There are no plans to include a fallback connection manager.  You should be prompted to provide a Connection URL that will be used if converse cannot determine one automatically from the host-meta file.

**Comment by DevCleverton** [comment]
> 
@Rakdos8
> **for me it is doing a loading loop, creating a registry, in windows**
